import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-orange">
      <Head>
        <title>SwayFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col flex-1 min-h-screen justify-center items-center p-16 mx-auto">
        <span>
            <Image src="/swayfit_logo.svg" alt="SwayFit Logo" width={653} height={400} />
        </span>
        <button className="px-2 py-2 rounded-md bg-purple cursor-pointer hover:bg-purple text-white text-xl font-semibold duration-100">
          Connect Wallet
        </button>
      </main>
    </div>
  )
}
